modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="iscript"
version="1.0.0"
displayName="iScript"
logoFile="logo.png"
credits=""
authors="iScript Team"
description='''
RPG scripting mod for Minecraft 1.20.1.
NPCs, dialogs, quests, regions and scripting.
'''

[[dependencies.iscript]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.iscript]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="BOTH"