package com.iscript.imson.event;

public enum EventType {
    PLAYER_JOIN,
    PLAYER_LEAVE,
    PLAYER_DEATH,
    PLAYER_RESPAWN,
    BLOCK_BREAK,
    BLOCK_PLACE,
    ITEM_USE,
    ITEM_PICKUP,
    ITEM_TOSS,
    CHAT,
    ENTITY_DAMAGE,
    ENTITY_KILL,
    PLAYER_KILL_ENTITY,
    PLAYER_INTERACT_ENTITY,
    PLAYER_INTERACT_BLOCK,
    PLAYER_OPEN_CONTAINER,
    TICK,
    REGION_ENTER,
    REGION_EXIT,
    QUEST_COMPLETE,
    DIALOG_OPEN,
    PLAYER_ADVANCEMENT
}